# Generated by Django 4.0.3 on 2022-07-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_options_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product'},
        ),
    ]
