# Generated by Django 4.0.3 on 2022-07-15 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
    ]
